name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install allure
        mkdir allure-results
        mkdir allure-report
        mkdir allure-history
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest --alluredir=allure-results
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
